const ALLOWED_MOMENTS=new Set(['welcome','final_summary']);
const PLACEHOLDER=/^(REPLACE_WITH_|DISABLED|__SET|placeholder|SET_IN_ENV_)/i;
function value(env,key,fallback=''){return String(env?.[key]??fallback).trim()}
function enabled(env,key,fallback=false){return ['1','true','yes','on'].includes(value(env,key,String(fallback)).toLowerCase())}
function real(v){return Boolean(v)&&!PLACEHOLDER.test(v)}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function seconds(text){return Math.max(1,Math.ceil(String(text).trim().split(/\s+/).filter(Boolean).length/2.5))}
function allowedOrigin(request,env){var expected=value(env,'PUBLIC_APP_URL','https://westpeekproductions.com').replace(/\/$/,'');var origin=request.headers.get('origin');return !origin||origin===expected||(/^https:\/\/[a-z0-9-]+\.join-west-peek-main\.pages\.dev$/i.test(origin)&&enabled(env,'ALLOW_CLOUDFLARE_PREVIEW_ORIGIN',false))}
async function verifyTurnstile(request,env,token){var secret=value(env,'TURNSTILE_SECRET_KEY');if(!real(secret))return {ok:true,mode:'not_configured'};if(!token)return {ok:false,mode:'required'};var ip=request.headers.get('CF-Connecting-IP')||'';var body=new FormData();body.set('secret',secret);body.set('response',token);if(ip)body.set('remoteip',ip);try{var r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body});var data=await r.json();return {ok:data.success===true,mode:'verified'}}catch{return {ok:false,mode:'failed'}}}
async function callDid(env,text,moment){var key=value(env,'DID_API_KEY');var source=value(env,'DID_SOURCE_URL');if(!real(key)||!real(source))throw new Error('did_not_configured');var auth=/^Basic\s+/i.test(key)?key:'Basic '+key;var r=await fetch(value(env,'DID_API_BASE_URL','https://api.d-id.com').replace(/\/$/,'')+'/talks',{method:'POST',headers:{authorization:auth,'content-type':'application/json'},body:JSON.stringify({source_url:source,script:{type:'text',input:text,provider:{type:value(env,'DID_VOICE_PROVIDER','microsoft'),voice_id:value(env,'DID_VOICE_ID','en-US-GuyNeural')}},config:{stitch:true,fluent:true},user_data:'west-peek-community-viability:'+moment})});var data=await r.json().catch(()=>({}));if(!r.ok||!data.id)throw new Error('did_request_failed');return data.id}
async function callHeyGen(env,text,moment){var key=value(env,'HEYGEN_API_KEY');var avatar=value(env,'HEYGEN_AVATAR_ID');var photo=value(env,'HEYGEN_TALKING_PHOTO_ID');var voice=value(env,'HEYGEN_VOICE_ID');if(!real(key)||(!real(avatar)&&!real(photo))||!real(voice))throw new Error('heygen_not_configured');var input={character:real(avatar)?{type:'avatar',avatar_id:avatar,avatar_style:'normal'}:{type:'talking_photo',talking_photo_id:photo},voice:{type:'text',input_text:text,voice_id:voice}};var r=await fetch(value(env,'HEYGEN_API_BASE_URL','https://api.heygen.com').replace(/\/$/,'')+'/v2/video/generate',{method:'POST',headers:{'x-api-key':key,'content-type':'application/json'},body:JSON.stringify({video_inputs:[input],dimension:{width:1280,height:720},test:enabled(env,'HEYGEN_TEST_MODE',false),title:'West Peek '+moment})});var data=await r.json().catch(()=>({}));var id=data?.data?.video_id;if(!r.ok||!id)throw new Error('heygen_request_failed');return id}
export async function onRequestPost({request,env}){
  if(!allowedOrigin(request,env))return json({status:'forbidden_origin',avatarReady:false},403);
  if(!enabled(env,'AVATAR_DYNAMIC_GENERATION_ENABLED',false))return json({status:'avatar_unavailable',avatarReady:false,reason:'Dynamic AI Scooter generation is disabled. Written results remain available.'},503);
  var body;try{body=await request.json()}catch{return json({status:'invalid_avatar_request',avatarReady:false},400)}
  var text=String(body?.text||'').trim(),moment=String(body?.moment||'').trim();var maxChars=Number(value(env,'AVATAR_MAX_SCRIPT_CHARS','1200'))||1200;var maxSeconds=moment==='welcome'?35:65;
  if(!ALLOWED_MOMENTS.has(moment)||!text||text.length>maxChars||seconds(text)>maxSeconds)return json({status:'invalid_avatar_request',avatarReady:false,reason:'The requested media moment or script is outside the approved limits.'},400);
  var human=await verifyTurnstile(request,env,body?.turnstileToken);if(!human.ok)return json({status:'human_verification_required',avatarReady:false},403);
  var order=Array.from(new Set([value(env,'AVATAR_PROVIDER','did').toLowerCase(),value(env,'AVATAR_SECONDARY_PROVIDER','heygen').toLowerCase()]));var failures=[];
  for(var provider of order){try{var id=provider==='did'?await callDid(env,text,moment):provider==='heygen'?await callHeyGen(env,text,moment):null;if(id)return json({status:'avatar_render_queued',avatarReady:false,provider,id,providerResponse:{id},moment,disclosure:'This is an AI-generated presentation of Scooter using his approved likeness.'},202)}catch(error){failures.push(provider+':'+String(error?.message||'provider_error'))}}
  console.error('avatar render failed',failures.join(','));return json({status:'avatar_unavailable',avatarReady:false,reason:'The managed avatar providers did not accept the render. Written results remain available.'},503)
}
export function onRequestGet(){return json({status:'method_not_allowed',avatarReady:false},405)}
